FROM node:22-alpine

WORKDIR /app/backend

RUN npm install -g pnpm@10

COPY Backend-sistema-bancario/package.json Backend-sistema-bancario/pnpm-workspace.yaml Backend-sistema-bancario/pnpm-lock.yaml ./
COPY Backend-sistema-bancario/auth-service/package.json ./auth-service/package.json
COPY Backend-sistema-bancario/account-service/package.json ./account-service/package.json
COPY Backend-sistema-bancario/points-service/package.json ./points-service/package.json

RUN pnpm install --frozen-lockfile

COPY Backend-sistema-bancario/ .

EXPOSE 3003

CMD ["pnpm", "--filter", "points-service", "start"]
