services:
  auth-service:
    build:
      context: ./Backend-sistema-bancario
      dockerfile: auth-service/Dockerfile
    container_name: sistema-bancario-auth
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3001:3001"
    volumes:
      - uploads_data:/app/backend/uploads
    networks:
      - sistema-bancario-network
    working_dir: /app/backend
    command: ["node", "auth-service/index.js"]

  account-service:
    build:
      context: ./Backend-sistema-bancario
      dockerfile: account-service/Dockerfile
    container_name: sistema-bancario-account
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3002:3002"
    volumes:
      - uploads_data:/app/backend/uploads
    networks:
      - sistema-bancario-network
    working_dir: /app/backend
    command: ["node", "account-service/index.js"]

  points-service:
    build:
      context: ./Backend-sistema-bancario
      dockerfile: points-service/Dockerfile
    container_name: sistema-bancario-points
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3003:3003"
    networks:
      - sistema-bancario-network
    working_dir: /app/backend
    command: ["node", "points-service/index.js"]

  frontend:
    build:
      context: ./Frontend-sistema-bancario
      dockerfile: Dockerfile
    container_name: sistema-bancario-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - auth-service
      - account-service
      - points-service
    networks:
      - sistema-bancario-network

networks:
  sistema-bancario-network:
    driver: bridge

volumes:
  uploads_data:
